# Generated by Django 4.2.7 on 2023-11-28 09:25

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='file',
            field=models.FileField(upload_to='file', validators=[myapp.validators.validate_any_extension]),
        ),
    ]
